name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.5.0

      - name: Install Dependencies
        run: |
          cd frontend
          npm ci

      - name: Run Cypress Tests
        run: |
          cd frontend
          npx cypress run